builders:
  reverse_asset_import:
    import: "package:reverse_asset_import/builder.dart"
    builder_factories: ["createFinalAssetsBuilder"]
    build_extensions:
      '.default.txt': ['.txt']
#     applies_builders:
#       - reverse_asset_import|default_files_cleanup
# post_process_builders:
#   default_files_cleanup:
#     import: "package:reverse_asset_import/builder.dart"
#     builder_factory: "defaultFilesCleanup"
#     defaults:
#       release_options:
#         enabled: true
