name: inject_assets_builder
version: 1.0.0
description: A builder that makes it possible for a package to access files from packages depending on it.
authors:
  - Philipp Schiffmann <philippschiffmann93@gmail.com>
homepage: https://github.com/pschiffmann/inject-assets-builder.dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  # Use a version that is compatible with Angular 5.0.0
  build: '>=0.12.7 <2.0.0'
  build_config: ^0.3.1+3
  meta: '>=0.9.0 <2.0.0'
dev_dependencies:
  build_test: ^0.10.3+3
  test: ^1.0.0
