targets:
  $default:
    builders:
      inject_scss_variables:
        enabled: true
        runs_before: ['sass_builder']
        generate_for:
          include:
            - 'lib/_variables.default.scss'

builders:
  inject_scss_variables:
    import: "package:inject_assets_builder/builder.dart"
    builder_factories: ["injectAssetsBuilder"]
    build_extensions:
      '.default.scss': ['.scss']
    defaults:
      options:
        file_extensions: ['.scss']
    runs_before:
      sass_builder
