global_options:
  my_components|inject_scss_variables:
    options:
      substitutions:
        "dep|_variables.default.scss": "app|_variables.scss"

targets:
  $default:
    builders:
      sass_builder:
        enabled: true
        generate_for:
          - web/styles.scss
