global_options:
  inject_assets_builder|inject_scss_files:
    options:
      asset_overrides:
        'my_components|lib/_variables.default.scss': 'app|lib/_variables.scss'

targets:
  $default:
    builders:
      sass_builder:
        enabled: true
        generate_for:
          - web/styles.scss
