global_options:
  my_components|inject_scss_variables:
    options:
      substitutions:
        "my_components|lib/_variables.default.scss": "app|lib/_variables.scss"

targets:
  $default:
    builders:
      sass_builder:
        enabled: true
        generate_for:
          - web/styles.scss
